Repository AY2324S2-CS2103T-F12-3/tp, pull requests merged in 2024-04, with the labels that each got.

#60 Add the ability to list the user's events and reminders for the
  src/main/java/tutorpro/logic/Messages.java
  src/main/java/tutorpro/logic/commands/ScheduleCommand.java
  src/main/java/tutorpro/logic/parser/AddressBookParser.java
  src/main/java/tutorpro/logic/parser/ScheduleCommandParser.java
  src/main/java/tutorpro/model/AddressBook.java
  src/main/java/tutorpro/model/Model.java
  src/main/java/tutorpro/model/ModelManager.java
  src/test/java/tutorpro/logic/commands/AddCommandTest.java
Labels: enhancement

#61 Fix truncated schedule
  src/main/java/tutorpro/model/ModelManager.java
  src/main/java/tutorpro/model/schedule/Reminder.java
  src/main/java/tutorpro/model/schedule/ReminderComparator.java
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/ScheduleWindow.css
  src/main/resources/view/ScheduleWindow.fxml
Labels: bug

#62 Add window for schedule
  src/main/java/tutorpro/logic/Logic.java
  src/main/java/tutorpro/logic/LogicManager.java
  src/main/java/tutorpro/logic/commands/ScheduleCommand.java
  src/main/java/tutorpro/logic/parser/EventCommandParser.java
  src/main/java/tutorpro/logic/parser/ParserUtil.java
  src/main/java/tutorpro/model/schedule/Event.java
  src/main/java/tutorpro/model/schedule/Reminder.java
  src/main/java/tutorpro/storage/JsonAdaptedReminder.java
  src/main/java/tutorpro/ui/MainWindow.java
  src/main/java/tutorpro/ui/ReminderCard.java
  src/main/java/tutorpro/ui/ReminderListPanel.java
  src/main/java/tutorpro/ui/ScheduleWindow.java
  src/main/resources/view/ReminderCard.fxml
  src/main/resources/view/ReminderListPanel.fxml
  src/main/resources/view/ScheduleWindow.css
  src/main/resources/view/ScheduleWindow.fxml
Labels: enhancement

#65 Update the user guide
  docs/UserGuide.md
  docs/images/Ui.png
Labels: documentation

#142 fix documentation bugs with find not documented to find parents
  docs/UserGuide.md
Labels: bug, documentation

#154 Fix #100: Update UserGuide.md
  docs/UserGuide.md
Labels: bug.functionality

#155 Fix #98: Update UserGuide.md
  docs/UserGuide.md
Labels: bug.functionality

#156 Remove schedule command
  docs/UserGuide.md
  src/main/java/tutorpro/logic/commands/ScheduleCommand.java
  src/main/java/tutorpro/logic/parser/AddressBookParser.java
  src/main/java/tutorpro/logic/parser/ScheduleCommandParser.java
  src/main/java/tutorpro/ui/MainWindow.java
  src/main/resources/view/MainWindow.fxml
  src/test/java/tutorpro/logic/parser/ScheduleCommandParserTest.java
Labels: bug.featureflaw

#157 Fix #123 and #120: update remind and event feature
  docs/UserGuide.md
Labels: bug.featureflaw

#171 Update xinyuan.md
  docs/team/xinyuan.md
Labels: documentation
